### PR TITLE
added m1ultra cpu test result

### PR DESCRIPTION
**Pull request by alexziskind1**

### CODE REVIEW

**Comment by rasbt** [comment]
Thanks for sending the results! I am actually quite surprised by the still very large runtime of 120 min! It's a 20-core CPU right? I expected it to be somewhat faster than the M1 pro CPU. Maybe there were several things running on the CPU already during the benchmark?

Screen Shot 2022-05-22 at 8 57 39 PM

**Comment by alexziskind1** [comment]
I was also pretty surprised by this. Yes 20 cores. Nothing else was running on the machine, as I turned it on just for this benchmark.

**Comment by rasbt** [comment]
No idea! That's a bit strange 🤔

**Comment by prachiagrl** [comment]
I got very similar results here - https://github.com/rasbt/machine-learning-notes/issues/12
Looks like there's a performance inversion on the CPU going from M1 Max to M1 Ultra. Maybe the die-to-die interposer used on the M1 Ultra is increasing the memory access latencies?

**Comment by rasbt** [comment]
Yeah, it's a bit strange but  maybe it's because of the die-to-die interpose like you said. It's been a while and I don't remember much of the architecture keynote though.
This benchmark here is almost identical to the M1 Pro though, maybe another explanation is that it's the performance ceiling due to how many CPU cores are used

**Pull request merged**
